apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::752546199810:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-15ESUPOTW5UVN
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::752546199810:role/UdacityFlaskDeployCBKubectlRole
       username: build
       groups:
         - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn: arn:aws:iam::752546199810:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-15ESUPOTW5UVN\n  username: system:node:{{EC2PrivateDNSName}}\n","mapUsers":"[]\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2020-12-29T12:15:31Z","managedFields":[{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:data":{".":{},"f:mapRoles":{},"f:mapUsers":{}}},"manager":"eksctl.exe","operation":"Update","time":"2020-12-29T12:15:31Z"},{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{}}}},"manager":"kubectl-client-side-apply","operation":"Update","time":"2020-12-29T12:21:47Z"}],"name":"aws-auth","namespace":"kube-system","resourceVersion":"2695","selfLink":"/api/v1/namespaces/kube-system/configmaps/aws-auth","uid":"7da25b11-3373-4323-89ee-9e4be5223b41"}}
  creationTimestamp: "2020-12-29T12:15:31Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2020-12-29T12:15:31Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2020-12-29T12:31:34Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "4330"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 7da25b11-3373-4323-89ee-9e4be5223b41
