apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::752546199810:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1R1CWZ6DWUE5F
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::752546199810:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-12-29T14:50:37Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2020-12-29T14:50:37Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1574"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 0938d40c-c618-483a-8c2e-2ddc49d05a66
